### ISSUE TITLE
Update README reflecting new configuration file

### ISSUE THREAD

**Issue by karlch** [chris-marsh/gcalendar#1]
Galendae seems to look for galendae.conf instead of galendaerc, presumably since commit d5377b1bafd6d1fd5bfd9e8796e9c2d19a47ff10. This should be reflected in the README.

By the way, highly enjoying galendae, keep up your great work!

**Comment by chris-marsh** [comment]
Thanks Kalrch, I had indeed missed some references to galendaerc. Fixed now.

**Comment by karlch** [comment]
Perfect!
