### ISSUE TITLE
Include <signal.h> header to define SIGTERM symbol

### ISSUE THREAD

**Issue by a-roy** [chris-marsh/gcalendar#4]
Tested using gcc version 7.2.0, Galendae does not compile because 'SIGTERM' is undeclared. The header file `<signal.h>` needs to be included in `src/instance.c`.

**Comment by chris-marsh** [comment]
Thanks a-roy. For some reason I had included SIGTERM from <sys/types.h> but this seems to have stopped working. I've changed the code as per your more sensible suggestion.
