### ISSUE TITLE
Start Week

### ISSUE THREAD

**Issue by TiagoDornelas** [chris-marsh/gcalendar#6]
Please, add a config option start_week

start_week=monday
or
start_week=sunday

in Brazil, the calendar is organized with Sunday starting the week

**Comment by chris-marsh** [comment]
Hi, this option should already be in the config file ... scroll to the bottom of the examples and you should see ...
```
# Sunday=0,   Monday=1, Tuesday=2, Wednesday=3
# Thursday=4, Friday=5, Saturday=6
week_start=0
```
